typography_spectrum: 0.4963097753934562
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1718513360247016
  lightness: 0.25260925851762295
  saturation: 0.9768034641165286
  rhythmicContrast: 0.9793541603721678
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5280162980780005
analytics:
  google: null
  facebook: null
  twitter: null
name: Denbar
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Denbar  Group
description: 'Real Estate, Technology, Consulting'
purpose: []
